version: "3.9"
services:
  orion_docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: orion_docker
    environment:
      - ROS_MASTER_URI=http://${HSR_IP}:11311
      - ROS_HOSTNAME=${YOUR_IP}
    extra_hosts:
      - "${HSR_HOSTNAME}:${HSR_IP}"
    network_mode: "host"
    tty: true
    volumes:
      - ../src:/orion_ws/src
